import AppKit
import ApplicationServices

/// Text injector
///
/// Uses clipboard + simulated ⌘V paste. Key details:
///
/// 1. **Post to `.cgSessionEventTap` (not `.cghidEventTap`)**.
///    On macOS 14+, keyboard events injected via `.cghidEventTap` can be silently dropped under stricter security policies;
///    `.cgSessionEventTap` operates at the user-session level and delivers Cmd+V to other apps more reliably.
///
/// 2. **After writing to the clipboard, wait 5ms for the OS to commit it** before posting Cmd+V.
///    NSPasteboard writes are non-atomic (changeCount increments immediately, but the actual content has a slight delay before it's visible across processes),
///    so posting Cmd+V immediately can occasionally cause the target app to paste stale clipboard content.
///
/// 3. **The user's clipboard survives intact.** Every item and every type on it (images, files, rich
///    text — not just the plain string) is snapshotted before the write and restored afterwards, and
///    the dictation itself is marked transient so clipboard-history managers don't record it.
///
/// 4. **No blocking waits.** Every pause is a `Task.sleep`, never `usleep`: this runs on the main
///    actor, which also services the hotkey's CGEventTap callback and the HUD animation, and a
///    blocked main thread is what gets an event tap disabled by timeout.
enum TextInjector {
    /// nspasteboard.org markers: "don't record this in clipboard history". Transient covers the
    /// write itself; AutoGenerated tells history tools it wasn't a user copy.
    private static let markerTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    /// How long the target gets to read the pasteboard before it is restored. ⌘V is handled
    /// asynchronously by the target, and slow readers (Electron apps, VMs, remote desktops) have been
    /// seen to take well over the old 0.5s — restoring early makes them paste the OLD clipboard.
    private static let restoreDelay: Duration = .milliseconds(900)

    /// The previous injection, including its clipboard restore. Injections run one at a time: two
    /// overlapping (a dictation finishing while Recent Dictations re-inserts) would otherwise
    /// snapshot each other's transient text and "restore" a dictation instead of the user's clipboard.
    @MainActor private static var previous: Task<Void, Never>?

    /// Returns once ⌘V has been posted; the clipboard restore finishes afterwards in the queue
    /// (`previous`), so the caller — and the dictation HUD — don't wait out the restore delay.
    @MainActor
    static func inject(text: String, to app: AppIdentity?, focusTarget: AXUIElement? = nil) async {
        guard !text.isEmpty else { return }
        let prior = previous
        await withCheckedContinuation { (pasted: CheckedContinuation<Void, Never>) in
            previous = Task { @MainActor in
                await prior?.value
                await performInjection(text: text, to: app, focusTarget: focusTarget, onPasted: { pasted.resume() })
            }
        }
    }

    /// One injection, start to finish — returns only after the clipboard has been restored.
    /// `onPasted` is called exactly once, right after ⌘V is posted.
    @MainActor
    private static func performInjection(
        text: String,
        to app: AppIdentity?,
        focusTarget: AXUIElement?,
        onPasted: () -> Void
    ) async {

        let pb = NSPasteboard.general

        // Save the whole current clipboard, every item and every type.
        let saved = PasteboardSnapshot(pb)
        let changeCountBeforeWrite = pb.changeCount

        // Write the text to be injected, marked transient for clipboard managers.
        pb.clearContents()
        pb.declareTypes([.string] + markerTypes, owner: nil)
        pb.setString(text, forType: .string)
        for marker in markerTypes { pb.setData(Data(), forType: marker) }
        let changeCountAfterWrite = pb.changeCount

        // Let the OS commit the clipboard content (visible across processes)
        try? await Task.sleep(for: .milliseconds(5))

        // Re-focus where dictation started. Without this, ⌘V lands in whatever window the user
        // clicked into while the (possibly long) transcription was still processing, so the
        // dictation gets pasted into the wrong place or lost. First bring the owning app forward
        // (only when we've actually drifted away, to avoid latency in the common case), then
        // restore focus to the exact text field via Accessibility.
        if let app,
           NSWorkspace.shared.frontmostApplication?.processIdentifier != app.processID,
           let running = NSRunningApplication(processIdentifier: app.processID) {
            running.activate()
            try? await Task.sleep(for: .milliseconds(120))   // let the app become frontmost before we re-focus
        }
        FocusTarget.restore(focusTarget)

        // Wait for the keyboard's modifier keys to be RELEASED before synthesizing ⌘V.
        //
        // Whether a modifier is still held when we post decides whether the target sees a clean ⌘V
        // or a ⌘⌥V that pastes nothing. Terminals in particular read the live/global modifier state,
        // so even an event whose own flags say "Command only" is reinterpreted with a still-held
        // Option. Poll until no command/option/shift/control is down (capped so a user who genuinely
        // holds the key can't hang injection), then post a clean ⌘V.
        let heldModifiers: CGEventFlags = [.maskCommand, .maskAlternate, .maskShift, .maskControl]
        var waitedMs = 0
        while waitedMs < 500,
              !CGEventSource.flagsState(.combinedSessionState).intersection(heldModifiers).isEmpty {
            try? await Task.sleep(for: .milliseconds(15))
            waitedMs += 15
        }

        // Simulate ⌘V — posted to cgSessionEventTap (more reliable than cghidEventTap on macOS 14+).
        // `.combinedSessionState` is the proven-reliable delivery source; with modifiers now
        // confirmed clear above, it can't contaminate the paste with a stray flag.
        let source = CGEventSource(stateID: .combinedSessionState)
        let keyDown = CGEvent(keyboardEventSource: source, virtualKey: 0x09, keyDown: true)
        let keyUp = CGEvent(keyboardEventSource: source, virtualKey: 0x09, keyDown: false)
        keyDown?.flags = .maskCommand
        keyUp?.flags = .maskCommand
        keyDown?.post(tap: .cgSessionEventTap)
        keyUp?.post(tap: .cgSessionEventTap)
        onPasted()

        // Log changeCount purely as a diagnostic. NOTE: this is NOT a reliable success/failure
        // signal — ⌘V *reads* the pasteboard, it doesn't write, so a perfectly successful paste
        // leaves changeCount UNCHANGED (touched=N is the normal case). It only flips to Y when
        // something else mutates the pasteboard (a clipboard-history manager, an app that
        // copies-on-paste). So don't gate UI on it — the log is for debugging only.
        let appBundle = app?.bundleID ?? "unknown"
        Logger.log(
            "Injector",
            "Pasted to \(appBundle) cc=\(changeCountBeforeWrite)→\(changeCountAfterWrite) saved=\(saved.summary)"
        )

        // Restore the clipboard once the target has had time to read it — but only if nothing else
        // has written to it since (the user copying something new must win). Awaited, so the next
        // queued injection can't start until this one has handed the clipboard back.
        try? await Task.sleep(for: restoreDelay)
        guard pb.changeCount == changeCountAfterWrite else {
            Logger.log("Injector", "Clipboard changed since paste; not restoring")
            return
        }
        saved.restore(to: pb)
    }
}

/// A full copy of a pasteboard's contents: every item, every type, as raw data.
///
/// Reading `data(forType:)` forces any lazily-promised representation, which is the point — the
/// owner of a promise may be gone by the time we restore. Types that yield no data are skipped.
@MainActor
private struct PasteboardSnapshot {
    private let items: [[(NSPasteboard.PasteboardType, Data)]]

    init(_ pb: NSPasteboard) {
        items = (pb.pasteboardItems ?? []).map { item in
            item.types.compactMap { type in
                item.data(forType: type).map { (type, $0) }
            }
        }.filter { !$0.isEmpty }
    }

    var summary: String {
        items.isEmpty ? "empty" : "\(items.count) item(s)/\(items.reduce(0) { $0 + $1.count }) type(s)"
    }

    func restore(to pb: NSPasteboard) {
        pb.clearContents()
        guard !items.isEmpty else { return }
        let restored = items.map { reps -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in reps { item.setData(data, forType: type) }
            return item
        }
        pb.writeObjects(restored)
    }
}
