import Foundation

/// ~/.we/ data directory management (the single authoritative entry point)
///
/// All code accessing ~/.we/ should go through this enum, rather than writing literal strings like `WEDataDir.url.appendingPathComponent("foo")`.
///
/// Directory tree (including the Phase B planned archive subdirectories):
///
///   ~/.we/
///     ├─ config.json                     runtime configuration
///     ├─ debug.log                       global log
///     ├─ correction-dictionary.json      mistranscription dictionary (used by the distillation pipeline)
///     ├─ dictionary.json                 user's private terminology array (used by SA contextualStrings)
///     ├─ personal-context.md             user's free-text personal context (injected into L2 polish/summary prompts)
///     ├─ voice-history.jsonl             live recording history
///     ├─ meeting-history.jsonl           per-segment L2 streaming record for meetings
///     ├─ corrections.jsonl               user manual corrections (if enabled)
///     ├─ audio/                          recording wavs
///     ├─ meetings/                       meeting exports (markdown)
///     ├─ models/                         local models (placeholder)
///     ├─ archive/                        archive: historical training snapshots / dictionary review intermediates / reports
///     │   ├─ dictionaries/
///     │   ├─ training-snapshots/
///     │   ├─ test-sets/
///     │   └─ reports/
///     └─ kpi/                            KPI monthly results archive
///
/// Behavior: `ensureExists()` creates all of the above subdirectories (if they don't exist); files are created on demand by each component the first time it writes.
enum WEDataDir {
    /// Root directory URL.
    static let url: URL = {
        FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent(".we")
    }()

    // MARK: - Subdirectory helpers (active directories)

    static var audio: URL    { url.appendingPathComponent("audio") }
    static var meetings: URL { url.appendingPathComponent("meetings") }
    static var models: URL   { url.appendingPathComponent("models") }
    static var kpi: URL      { url.appendingPathComponent("kpi") }

    // MARK: - Subdirectory helpers (archive / evaluation artifacts, Phase B planned)

    static var archive: URL                  { url.appendingPathComponent("archive") }
    static var archiveDictionaries: URL      { archive.appendingPathComponent("dictionaries") }
    static var archiveTrainingSnapshots: URL { archive.appendingPathComponent("training-snapshots") }
    static var archiveTestSets: URL          { archive.appendingPathComponent("test-sets") }
    static var archiveReports: URL           { archive.appendingPathComponent("reports") }

    // MARK: - Active filename constants (avoids scattered string literals)

    enum FileName {
        static let config            = "config.json"
        static let log               = "debug.log"
        static let voiceHistory      = "voice-history.jsonl"
        static let meetingHistory    = "meeting-history.jsonl"
        static let corrections       = "corrections.jsonl"
        static let correctionDict    = "correction-dictionary.json"
        static let contextualDict    = "dictionary.json"            // used for SA contextualStrings, documented in the README
        static let personalContext   = "personal-context.md"        // free-text personal context, injected into polish/summary prompts
    }

    // MARK: - Full file URL shortcuts

    static var configURL: URL         { url.appendingPathComponent(FileName.config) }
    static var logURL: URL            { url.appendingPathComponent(FileName.log) }
    static var voiceHistoryURL: URL   { url.appendingPathComponent(FileName.voiceHistory) }
    static var meetingHistoryURL: URL { url.appendingPathComponent(FileName.meetingHistory) }
    static var correctionsURL: URL    { url.appendingPathComponent(FileName.corrections) }
    static var correctionDictURL: URL { url.appendingPathComponent(FileName.correctionDict) }
    static var personalContextURL: URL { url.appendingPathComponent(FileName.personalContext) }

    // MARK: - Derived paths (generated by timestamp)

    /// Generate an audio/*.wav path (does not create the file)
    static func audioURL(forName name: String, ext: String = "wav") -> URL {
        audio.appendingPathComponent("\(name).\(ext)")
    }

    /// Generate an audio/remote-*.wav path
    static func remoteAudioURL(timestamp: String) -> URL {
        audio.appendingPathComponent("remote-\(timestamp).wav")
    }

    /// Generate a meetings/*.md path
    static func meetingMarkdownURL(forName name: String) -> URL {
        meetings.appendingPathComponent("\(name).md")
    }

    /// Resolve the user-configured meeting save folder (supports ~ expansion). Falls back to the default meetings directory when nil/empty.
    /// Resolve the user-configured meetings save folder (expands ~). Falls back to `meetings`.
    static func resolveMeetingsFolder(_ path: String?) -> URL {
        guard let path, !path.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            return meetings
        }
        let expanded = (path as NSString).expandingTildeInPath
        return URL(fileURLWithPath: expanded, isDirectory: true)
    }

    // MARK: - Initialization

    /// Ensure all active / archive subdirectories exist
    static func ensureExists() {
        let fm = FileManager.default
        let dirs: [URL] = [
            url,
            audio,
            meetings,
            models,
            kpi,
            archive,
            archiveDictionaries,
            archiveTrainingSnapshots,
            archiveTestSets,
            archiveReports,
        ]
        for dir in dirs {
            if !fm.fileExists(atPath: dir.path) {
                try? fm.createDirectory(at: dir, withIntermediateDirectories: true)
            }
        }
        Logger.log("DataDir", "Ensured ~/.we/ structure exists")
    }
}
